### ISSUE TITLE
material-table可以做到像antd表格这样添加边框吗

### ISSUE THREAD

**Issue by zhushenhang** [SimpleRoom/walker-admin#1]
![image](https://user-images.githubusercontent.com/24982716/82990448-cf97e700-a02e-11ea-9724-7ef074067d3d.png)

**Comment by zhushenhang** [comment]
我已经在官方文档找到了方法

**Comment by jiucheng-front** [comment]
得看官方文档的

zhushenhang ***@***.***> 于2020年5月27日周三 16:08写道：
